# Generated by Django 3.1.4 on 2021-01-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment_lend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BelongingsImformation',
            fields=[
                ('equipment_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('property_number', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=20)),
                ('property_name', models.CharField(max_length=20)),
                ('property_price', models.CharField(max_length=20)),
                ('purchase_date', models.DateTimeField(auto_now=True)),
                ('placement', models.CharField(max_length=20)),
                ('property_status', models.CharField(max_length=20)),
                ('company_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company_information',
            fields=[
                ('company_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_editor', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=20)),
                ('company_contact_name', models.CharField(max_length=20)),
                ('company_contact_email', models.EmailField(max_length=30)),
                ('company_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LendRecord',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('equipment_id', models.CharField(max_length=20)),
                ('lend_date', models.DateTimeField(auto_now_add=True)),
                ('borrow_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('user_class', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=30)),
                ('user_phone', models.CharField(max_length=10)),
            ],
        ),
    ]
